"""Add unsubscribe behaviour

Revision ID: b0101a66bb77
Revises: bd7d032087b2
Create Date: 2022-07-06 19:52:04.324761

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0101a66bb77'
down_revision = 'bd7d032087b2'
branch_labels = None
depends_on = None

def get_enum() -> postgresql.ENUM:
    return postgresql.ENUM('DisableAlias', 'PreserveOriginal', name='unsubscribe_behaviour_enum')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    unsub_enum = get_enum()
    unsub_enum.create(op.get_bind())
    op.add_column('users', sa.Column('unsub_behaviour', unsub_enum, default='PreserveOriginal', server_default='DisableAlias', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unsub_behaviour')
    unsub_enum = get_enum()
    unsub_enum.drop(op.get_bind())
    # ### end Alembic commands ###